kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: voter
  name: voter
spec:
  replicas: 1
  selector:
    matchLabels:
     app: voter
  template:
    metadata:
      labels:
        app: voter
    spec:
      containers:
        - name: voter
          image: mateobur/voter:tags
          env:
            - name: VOTE
              value: "vote.eva.svc.cluster.local"
            - name: PORT
              value: "5000"

